[package]
name = "invoice-harness"
version = "0.1.1"
entrypoint = "src/lib.typ"
authors = ["Niklas Eicker <git@nikl.me>"]
license = "MIT"
description = "Simplify creating ZUGFeRD electronic invoices"
homepage = "https://github.com/oicana/invoice-harness"
repository = "https://github.com/oicana/invoice-harness"
keywords = ["zugferd", "invoice"]
categories = ["scripting", "utility"]
compiler = "0.13.0"
exclude = ["*/tests/**"]
